(**** Replicator 1 & 2 leveling script ****)
(**** Do not run on Thing-o-Matics or Cupcakes: their homing is backwards ***)
M103 (disable RPM)
M73 P0 (enable build progress)
G21 (set units to mm)
G90 (set positioning to absolute)
(**** Begin homing ****)
G162 X Y F2500 (home XY axes maximum)
G161 Z F1100 (home Z axis minimum)
G92 Z-5 (set Z to -5)
G1 Z0.0 F1100 (move Z to "0")
G161 Z F100 (home Z axis minimum)
M132 X Y Z A B (Recall stored home offsets)
(**** End homing ****)
(**** Move to the center of platform using two moves.  First move with  ****)
(**** the platform 10 mm below the extruder and thus unlikely to scrape ****)
(**** across it.  Second move raising the platform to Z=0 and thus just ****)
(**** below the nozzle assuming the home offsets are correct.           ****)
G1 X0 Y0 Z10 F1100.0 (Move to [0,0,10]; unaccelerated owing to prior M132)
G1 Z0 F1100.0 (Move to [0,0,0]; accelerated)
(**** Disable the X & Y stepper motors so that the nozzle can be moved ****)
(**** about to any position over the platform allowing multi-point     ****)
(**** leveling and testing with a dial indicator or other test guage.  ****)
M18 X Y A B (Leave Z stepper enabled; disable the others)
M71 (Press "M" when level)
(**** All done -- disable all the stepper motors ****)
M18 X Y Z A B (Disable all stepper motors)
