# Parameters
platform = 'test'

src_dir = '../../src'
build_dir = 'build/'+platform+'/core'
VariantDir(build_dir,src_dir)

test_src_dir='src'
test_build_dir='build/'+platform+'/test'
VariantDir(test_build_dir,test_src_dir)

gtest_home = '..'

flags='-I'+src_dir+'/shared -I'+src_dir+'/'+platform

env=Environment(CCFLAGS=flags)
program=env.Program([test_build_dir+'/T1-UART-exerciser.cc',build_dir+'/shared/Packet.cc'])
run_alias = env.Alias('run', [program], program[0].path)
AlwaysBuild(run_alias)