#ifndef BOARDID_HH_
#define BOARDID_HH_

#define BOARD_TYPE_MIGHTYBOARD_E 1
#define BOARD_TYPE_MIGHTYBOARD_G 2
#define BOARD_TYPE_MIGHTYBOARD_H ( BOARD_TYPE_MIGHTYBOARD_G )
#define BOARD_TYPE_AZTEEG_X3 3

#endif // BOARDID_HH_
