#
# HOW TO USE THIS BUILD SCRIPT
#
# By default, this script will build the firmware for an atmega168-based extruder controller.
# The firmware will be built, but not uploaded.
#
# To build for another platform, pass an explicit platform parameter.  For example,
# $ scons platform=ecv22
# $ scons platform=ecv34
#
# To default to stepper rather than DC drive, add "stepper=true".
# To default to PWM heater rather than relays, add "relays=false".
#
# To upload the firmware, specify the "upload" target.  By default, this will use
# /dev/ttyUSB0 as the serial connection.
# $ scons upload
#
# If you want to select a port manually, specify it as a parameter:
# $ scons port=/dev/ttyUSB3 upload
#

import os
import re
from os.path import dirname
# Parameters
platform = ARGUMENTS.get('platform','ecv22')
stepper = ARGUMENTS.get('stepper','false')
extstepper = ARGUMENTS.get('extstepper','false')
f_cpu='16000000L'

if platform == 'ec36':
	platform = 'ecv34'
	
default_baud = '19200'
mcu='atmega168'
has_queue = 0
has_psu = 0


def parse_version(v):
    if not v:
        return 0
    if v.find(".") != -1:
       parts = v.split(".")
       return (int(parts[0]) * 100) + int(parts[1])
    return int(v)

def get_default_version():
	regex = re.compile(r"const uint16_t firmware_version = ([0-9]+);")
	return parse_version(f.get_contents().strip())

vstr = File('#/current_version.txt').get_contents().strip()

vstr = ARGUMENTS.get('version',vstr)

version = parse_version(vstr)

if (platform == 'ecv22'):
	default_baud = '19200'
	mcu='atmega168'
	has_queue = 0
	has_psu = 0
	relays_default = 'true'
elif (platform == 'ecv34'):
	default_baud = '19200'
	mcu='atmega168'
	has_queue = 0
	has_psu = 0
	relays_default = 'false'
else:
	print "Platform "+platform+" is not currently supported.\n"
	exit()

relays = ARGUMENTS.get('relays',relays_default)

target_name = "EC-"+platform+"-v"+str(version//100)+"."+str(version%100)

upload_port = ARGUMENTS.get('port','/dev/ttyUSB1')
upload_baud = ARGUMENTS.get('baud',default_baud)
upload_prog = ARGUMENTS.get('programmer','stk500v1')

srcs = Glob('*.cc') + Glob('boards/%s/*.cc' % platform) + Glob('#/src/shared/*.cc')

include_paths = ['#/src/shared', 'boards/%s' % platform, '.']

flags=[
	'-DF_CPU='+str(f_cpu),
	'-DVERSION='+str(version),
	'-mmcu='+mcu,
	'-g',
	'-Os',
	'-w',
	'-fno-exceptions',
	'-ffunction-sections',
	'-fdata-sections']

if (os.environ.has_key('BUILD_NAME')):
   flags.append('-DBUILD_NAME=' + os.environ['BUILD_NAME'])

if (stepper == 'true'):
   flags.append('-DDEFAULT_STEPPER=1')

if (extstepper == 'true'):
   flags.append('-DDEFAULT_EXTERNAL_STEPPER=1')

if (relays == 'true'):
   flags.append('-DDEFAULT_RELAYS=1')

if (os.environ.has_key('AVR_TOOLS_PATH')):
	avr_tools_path = os.environ['AVR_TOOLS_PATH']
elif (os.environ.has_key('AVR32_HOME')):
	avr_tools_path = os.environ['AVR32_HOME'] + '\\bin'
else:
	avr_tools_path = dirname(os.popen('/usr/bin/which avr-gcc').readlines()[0])

env=Environment(tools=['g++', 'gcc'],
	CC=avr_tools_path+"/avr-gcc",
	CXX=avr_tools_path+"/avr-g++",
	CPPPATH=include_paths,
	CCFLAGS=flags)
objs = env.Object(srcs)

# run_alias = Alias('run', [program], program[0].path)
# AlwaysBuild(run_alias)

hex_name = target_name + '.hex'
elf_name = target_name + '.elf'

env.Append(BUILDERS={'Elf':Builder(action=avr_tools_path+"/avr-gcc -mmcu="+mcu+" -Wl,-Map=${TARGET}.map -Os -Wl,--gc-sections -o $TARGET $SOURCES")})
env.Append(BUILDERS={'Hex':Builder(action=avr_tools_path+"/avr-objcopy -O ihex -R .eeprom $SOURCES $TARGET")})
env.Elf(elf_name, objs) 
env.Hex(hex_name, elf_name)

avrdude = avr_tools_path+"/avrdude"
avrdude_flags = "-V -p"+mcu # +mcu.replace("atmega","m")
avrdude_flags = avrdude_flags + " -P "+upload_port
avrdude_flags = avrdude_flags + " -c "+upload_prog
avrdude_flags = avrdude_flags + " -b "+upload_baud
avrdude_command = " ".join([avrdude,avrdude_flags,"-U","flash:w:$SOURCES"])

# env.Alias instead of just Alias because of
# http://scons.tigris.org/issues/show_bug.cgi?id=2443
upload_alias = env.Alias('upload', hex_name, avrdude_command)
AlwaysBuild(upload_alias)
